###################################################################

# Created by write_sdc on Fri Mar 31 22:48:15 2023

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_load -pin_load 0.05 [get_ports {C1X[3]}]
set_load -pin_load 0.05 [get_ports {C1X[2]}]
set_load -pin_load 0.05 [get_ports {C1X[1]}]
set_load -pin_load 0.05 [get_ports {C1X[0]}]
set_load -pin_load 0.05 [get_ports {C1Y[3]}]
set_load -pin_load 0.05 [get_ports {C1Y[2]}]
set_load -pin_load 0.05 [get_ports {C1Y[1]}]
set_load -pin_load 0.05 [get_ports {C1Y[0]}]
set_load -pin_load 0.05 [get_ports {C2X[3]}]
set_load -pin_load 0.05 [get_ports {C2X[2]}]
set_load -pin_load 0.05 [get_ports {C2X[1]}]
set_load -pin_load 0.05 [get_ports {C2X[0]}]
set_load -pin_load 0.05 [get_ports {C2Y[3]}]
set_load -pin_load 0.05 [get_ports {C2Y[2]}]
set_load -pin_load 0.05 [get_ports {C2Y[1]}]
set_load -pin_load 0.05 [get_ports {C2Y[0]}]
set_load -pin_load 0.05 [get_ports DONE]
set_ideal_network -no_propagate  [get_ports CLK]
create_clock [get_ports CLK]  -period 8  -waveform {0 4}
set_input_delay -clock CLK  0  [get_ports CLK]
set_input_delay -clock CLK  0  [get_ports RST]
set_input_delay -clock CLK  4  [get_ports {X[3]}]
set_input_delay -clock CLK  4  [get_ports {X[2]}]
set_input_delay -clock CLK  4  [get_ports {X[1]}]
set_input_delay -clock CLK  4  [get_ports {X[0]}]
set_input_delay -clock CLK  4  [get_ports {Y[3]}]
set_input_delay -clock CLK  4  [get_ports {Y[2]}]
set_input_delay -clock CLK  4  [get_ports {Y[1]}]
set_input_delay -clock CLK  4  [get_ports {Y[0]}]
set_output_delay -clock CLK  4  [get_ports {C1X[3]}]
set_output_delay -clock CLK  4  [get_ports {C1X[2]}]
set_output_delay -clock CLK  4  [get_ports {C1X[1]}]
set_output_delay -clock CLK  4  [get_ports {C1X[0]}]
set_output_delay -clock CLK  4  [get_ports {C1Y[3]}]
set_output_delay -clock CLK  4  [get_ports {C1Y[2]}]
set_output_delay -clock CLK  4  [get_ports {C1Y[1]}]
set_output_delay -clock CLK  4  [get_ports {C1Y[0]}]
set_output_delay -clock CLK  4  [get_ports {C2X[3]}]
set_output_delay -clock CLK  4  [get_ports {C2X[2]}]
set_output_delay -clock CLK  4  [get_ports {C2X[1]}]
set_output_delay -clock CLK  4  [get_ports {C2X[0]}]
set_output_delay -clock CLK  4  [get_ports {C2Y[3]}]
set_output_delay -clock CLK  4  [get_ports {C2Y[2]}]
set_output_delay -clock CLK  4  [get_ports {C2Y[1]}]
set_output_delay -clock CLK  4  [get_ports {C2Y[0]}]
set_output_delay -clock CLK  4  [get_ports DONE]
